baseURL = "https://shooting-star-blog.com/"
locale = "he-IL"
defaultContentLanguage = "he"
title = "כוכב נופל"
enableRobotsTXT = true

[params]
  description = "סיפורי מדע בדיוני ופנטזיה קצרים מאת ש.מ"
  author = "ש.מ"
  contactEmail = "contact@shooting-star-blog.com"
  contactFormEndpoint = "https://shooting-star-contact.shootingstarblog.workers.dev"
  turnstileSiteKey = "0x4AAAAAAEQLhHRIzv5JfsbT"
  umamiSiteId = "3f8b449d-9a37-4f79-b838-d949d6f2ef85"

[taxonomies]
  tag = "tags"

[pagination]
  pagerSize = 15

[imaging.webp]
  quality = 75

[markup.goldmark.renderer]
  unsafe = true
